platform: linux
image: "docker:///python#2.7.11-slim"
inputs:
  - name: photography
  - name: version
  - name: candidate-release
outputs:
  - name: deployable_artifacts
run:
  path: photography/ci/create-deployment.sh
