platform: linux

image: docker:///ubuntu

inputs:
  - name: photography
  - name: version
  - name: photography-rc
  
outputs:
  - name: deployment
  
run:
  path: photography/ci/create-deployment.sh
