platform: linux
image: "docker:///richardkdrew/docker-node-grunt-bower"
inputs:
  - name: photography
  - name: version
  - name: candidate-release
outputs:
  - name: deployable_artifacts
run:
  path: photography/ci/create-deployment.sh
