resource_types:
- name: s3-sync
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple

resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri-bump-semver}}
    branch: version
    file: version
    private_key: {{github-private-key}}

- name: photography
  type: git
  source:
    uri: {{git-uri-photography}}
    branch: develop
    private_key: {{github-private-key}}

- name: photography-master
  type: git
  source:
    uri: {{git-uri-photography}}
    branch: master
    private_key: {{github-private-key}}

- name: deployments
  type: git
  source:
    uri: {{bitbucket-uri-photography}}
    branch: master
    private_key: {{bitbucket-private-key}}

- name: final-release
  type: github-release
  source:
    user: richardkdrew
    repository: rd-photography
    access_token: {{photography-release-access-token}}

- name: candidate-release
  type: s3
  source:
    region_name: ap-northeast-1
    bucket: photography-pipeline-artifacts
    regexp: photography-(.v*).tgz
    access_key_id: {{photography-s3-access-key-id}}
    secret_access_key: {{photography-s3-secret-access-key}}

- name: aws-deployment
  type: s3-sync
  source:
    bucket: rd-photography
    access_key_id: {{photography-s3-access-key-id}}
    secret_access_key: {{photography-s3-secret-access-key}}
    options: [
      '--dryrun',
      '--exclude "*"',
      '--include "deployment/*"',
      '--cache-control max-age=604800'
    ]

jobs:
- name: unit
  public: true
  serial: true
  plan:
  - get: photography
    trigger: true
  - task: install-dependencies
    file: photography/ci/install-dependencies.yml
  - task: unit-test
    file: photography/ci/unit.yml

- name: rc
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: photography
      passed: [unit]
      trigger: true
    - get: version
      params: {pre: rc}
  - put: version
    params: {file: version/number}

- name: build-rc
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: photography
      passed: [rc]
      trigger: true
    - get: version
      passed: [rc]
      trigger: true
  - task: install-dependencies
    file: photography/ci/install-dependencies.yml
  - task: build-artifacts
    file: photography/ci/build-artifacts.yml
  - put: candidate-release
    params: {file: build_artifacts/photography-*.tgz}

- name: testflight
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: deployments
      trigger: true
    - get: candidate-release
      passed: [build-rc]
      trigger: true
    - get: photography
      passed: [build-rc]
      trigger: true
    - get: version
      passed: [build-rc]
      trigger: true
  - task: perform-testflight
    file: photography/ci/perform-testflight.yml

- name: deploy
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: candidate-release
      passed: [testflight]
      trigger: true
    - get: photography
      passed: [testflight]
      trigger: true
    - get: version
      passed: [testflight]
      trigger: true
  - task: create-deployment
    file: photography/ci/create-deployment.yml
  - put: aws-deployment

- name: shipit
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: photography
      passed: [deploy]
    - get: candidate-release
      passed: [deploy]
    - get: version
      params: {bump: final}
      passed: [deploy]
  - task: promote-to-master
    file: photography/ci/merge-master.yml
  - put: photography-master
    params: {repository: photography-merged}
  - task: create-release
    file: photography/ci/create-release.yml
  - put: final-release
    params:
      name: release/name
      tag: release/tag
      body: release/body
      globs: [release/artifacts/*]

- name: master-merge
  plan:
  - aggregate:
    - get: photography-master
      params: {submodules: none}
      trigger: true
    - get: photography
      params: {submodules: none}
  - task: merge-to-develop
    file: photography/ci/merge-master.yml
  - put: photography-master
    params: {repository: photography-merged}

- name: create-pre-release
  plan:
  - aggregate:
    - get: candidate-release
      passed: [build-rc]
      trigger: true
    - get: photography
      passed: [build-rc]
      trigger: true
    - get: version
      passed: [build-rc]
      trigger: true
  - task: create-pre-release
    file: photography/ci/create-pre-release.yml
  - task: generate-commitish
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: {repository: concourse/git-resource}

      inputs:
      - name: photography

      outputs:
      - name: generated-commitish

      run:
        path: sh
        args:
        - -c
        - |
          git -C photography rev-parse HEAD > generated-commitish/commitish
  - put: final-release
    params:
      name: pre-release/name
      tag: pre-release/tag
      body: pre-release/body
      globs: [pre-release/artifacts/*]
      commitish: generated-commitish/commitish
      prerelease: true

- name: minor
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: major
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/number}

- name: patch
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    trigger: true
  - put: version
    params: {bump: patch, pre: rc}

groups:
- name: photography
  jobs:
  - create-pre-release
  - master-merge
  - unit
  - rc
  - build-rc
  - testflight
  - deploy
  - shipit
  - patch
  - major
  - minor
