resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri-bump-semver}}
    branch: version
    file: version
    private_key: {{github-private-key}}

- name: photography
  type: git
  source:
    uri: {{git-uri-photography}}
    branch: develop
    private_key: {{github-private-key}}

- name: photography-releases
  type: github-release
  source:
    user: richardkdrew
    repository: photography
    access_token: {{github-private-key}}

jobs:
- name: unit
  public: true
  serial: true
  plan:
  - get: photography
    trigger: true
  - task: install-dependencies
    file: photography/ci/install-dependencies.yml
  - task: unit-test
    file: photography/ci/unit.yml

- name: rc
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: photography
      passed: [unit]
      trigger: true
    - get: version
      params: {pre: rc}
  - task: install-dependencies
    file: photography/ci/install-dependencies.yml
  - task: build-artifacts
    file: photography/ci/build-artifacts.yml
  - task: build-release
    file: photography/ci/build-release.yml
  - put: version
    params: {file: version/number}
  - put: photography-releases
    params:
    name: release/name
    tag: release/tag
    body: release/body
    globs: [release/artifacts/*]

- name: minor
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: major
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/number}

groups:
- name: photography
  jobs:
  - unit
  - rc
  - major
  - minor
