resource_types:
- name: s3-sync
  type: docker-image
  source:
    repository: 18fgsa/s3-resource-simple
    
resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri-bump-semver}}
    branch: version
    file: version
    private_key: {{github-private-key}}

- name: photography
  type: git
  source:
    uri: {{git-uri-photography}}
    branch: develop
    private_key: {{github-private-key}}

- name: photography-rc
  type: github-release
  source:
    user: richardkdrew
    repository: rd-photography
    access_token: {{photography-release-access-token}}


- name: aws-deployment
  type: s3-sync
  source:
    bucket: rd-photography
    access_key_id: {{photography-s3-access-key-id}}
    secret_access_key: {{photography-s3-secret-access-key}}
    options: [
      '--dryrun',
      '--exclude "photography"',
      '--exclude "photography-rc"',
      '--exclude "version"',
      '--cache-control max-age=604800'
    ]

jobs:
- name: unit
  public: true
  serial: true
  plan:
  - get: photography
    trigger: true
  - task: install-dependencies
    file: photography/ci/install-dependencies.yml
  - task: unit-test
    file: photography/ci/unit.yml

- name: rc
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: photography
      passed: [unit]
      trigger: true
    - get: version
      params: {pre: rc}
  - put: version
    params: {file: version/number}

- name: build-rc
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: photography
      passed: [rc]
      trigger: true
    - get: version
      passed: [rc]
      trigger: true
  - task: install-dependencies
    file: photography/ci/install-dependencies.yml
  - task: build-artifacts
    file: photography/ci/build-artifacts.yml
  - task: build-release
    file: photography/ci/build-release.yml
  - put: photography-rc
    params:
      name: release/name
      tag: release/tag
      body: release/body
      globs: [release/artifacts/*]

- name: deploy
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: photography-rc
      passed: [build-rc]
      trigger: true
    - get: photography
      passed: [build-rc]
      trigger: true
    - get: version
      passed: [build-rc]
      trigger: true
  - task: create-deployment
    file: photography/ci/create-deployment.yml
  - put: aws-deployment

- name: minor
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: major
  public: true
  serial: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/number}

groups:
- name: photography
  jobs:
  - unit
  - rc
  - build-rc
  - deploy
  - major
  - minor
